name: test_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter

  http: ^1.1.0
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  collection: ^1.15.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/deepcompany_logo.jpg
